random_seed: 12345 


fov: 20
timestep: 0.01
n_sim_steps: 5
num_beams: 0

vehicle_width: 0.31
vehicle_length: 0.58

#MPCC params
vehicle_speed: 2

wheelbase: 0.33

weight_progress: 0
weight_lag: 1
weight_contour: 10
weight_steer: 1

p_initial: 2
delta_max: 0.4
p_min: 0
p_max: 4 

psi_min: -10
psi_max: 10

number_test_laps: 1
N: 3
map_name: "Oschersleben"

runs:
  # - n_sim_steps: 2
  #   test_id: 2
  - n_sim_steps: 3
    test_id: 3
  # - n_sim_steps: 4
  #   test_id: 4
  # - n_sim_steps: 5
  #   test_id: 5
  - n_sim_steps: 6
    test_id: 6
  # - n_sim_steps: 7
  #   test_id: 7
  # - n_sim_steps: 8
  #   test_id: 8
  - n_sim_steps: 9
    test_id: 9
  # - n_sim_steps: 10
  #   test_id: 10

