random_seed: 12345 


fov: 20
timestep: 0.01
num_beams: 0

vehicle_width: 0.31
vehicle_length: 0.58

#MPCC params
vehicle_speed: 2

wheelbase: 0.33

weight_progress: 0
weight_lag: 1
weight_contour: 10
weight_steer: 1

p_initial: 2
delta_max: 0.4
p_min: 0
p_max: 4 

psi_min: -10
psi_max: 10

number_test_laps: 1
# map_name: "Sepang"
map_name: "Oschersleben"

runs:
  # - N: 2
  #   n_sim_steps: 2
  #   test_id: "2x2"

  # - N: 2
  #   n_sim_steps: 4
  #   test_id: "2x4"

  # - N: 2
  #   n_sim_steps: 6
  #   test_id: "2x6"

  # - N: 2
  #   n_sim_steps: 8
  #   test_id: "2x8"

  # - N: 2
  #   n_sim_steps: 10
  #   test_id: "2x10"


  # - N: 4
  #   n_sim_steps: 2
  #   test_id: "4x2"

  # - N: 4
  #   n_sim_steps: 4
  #   test_id: "4x4"

  # - N: 4
  #   n_sim_steps: 6
  #   test_id: "4x6"

  # - N: 4
  #   n_sim_steps: 8
  #   test_id: "4x8"

  # - N: 4
  #   n_sim_steps: 10
  #   test_id: "4x10"


  # - N: 5
  #   n_sim_steps: 2
  #   test_id: "5x2"

  # - N: 5
  #   n_sim_steps: 6
  #   test_id: "5x6"

  # - N: 5
  #   n_sim_steps: 10
  #   test_id: "5x10"

  # - N: 6
  #   n_sim_steps: 2
  #   test_id: "6x2"

  # - N: 6
  #   n_sim_steps: 4
  #   test_id: "6x4"

  # - N: 6
  #   n_sim_steps: 6
  #   test_id: "6x6"

  # - N: 6
  #   n_sim_steps: 8
  #   test_id: "6x8"

  # - N: 6
  #   n_sim_steps: 10
  #   test_id: "6x10"


  # - N: 8
  #   n_sim_steps: 2
  #   test_id: "8x2"

  # - N: 8
  #   n_sim_steps: 4
  #   test_id: "8x4"

  # - N: 8
  #   n_sim_steps: 6
  #   test_id: "8x6"

  # - N: 8
  #   n_sim_steps: 8
  #   test_id: "8x8"

  # - N: 8
  #   n_sim_steps: 10
  #   test_id: "8x10"



  # - N: 10
  #   n_sim_steps: 2
  #   test_id: "10x2"

  - N: 10
    n_sim_steps: 4
    test_id: "10x4"

  # - N: 10
  #   n_sim_steps: 6
  #   test_id: "10x6"

  - N: 10
    n_sim_steps: 8
    test_id: "10x8"

  # - N: 10
  #   n_sim_steps: 10
  #   test_id: "10x10"


